language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
before_script: # => 6
  - psql postgres -e 'CREATE ROLE root LOGIN'
  - psql postgres -e 'create database tasker;' -u root
script:
  - python manage.py test
